# Generated by Django 4.2 on 2023-04-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commit',
            name='header',
            field=models.CharField(max_length=100),
        ),
    ]
